'use client';

import { useCallback, useEffect, useState } from 'react';

interface TopicWithStats {
  id: string;
  name: string;
  autoGenerated: boolean;
  promptCount: number;
  responseCount: number;
  visibilityPct: number;
}

interface PromptWithResponses {
  id: string;
  text: string;
  responses: {
    id: string;
    provider: string;
    hasMention: boolean;
    rank: number | null;
  }[];
}

interface LLMResponseDetail {
  id: string;
  provider: string;
  responseText: string;
  mentions: {
    brandName: string;
    rankPosition: number | null;
    isCited: boolean;
    context: string | null;
  }[];
  sources: {
    url: string;
    domain: string;
    title: string | null;
  }[];
}

export function useTopics(brandId: string) {
  const [data, setData] = useState<TopicWithStats[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchTopics = useCallback(async () => {
    if (!brandId) return;

    try {
      setIsLoading(true);
      const response = await fetch(`/api/brands/${brandId}/topics?withStats=true`);
      if (!response.ok) throw new Error('Failed to fetch topics');
      const result = await response.json();
      setData(result);
      setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unknown error');
    } finally {
      setIsLoading(false);
    }
  }, [brandId]);

  useEffect(() => {
    fetchTopics();
  }, [fetchTopics]);

  return { data, isLoading, error, refetch: fetchTopics };
}

export function usePrompts(topicId: string) {
  const [data, setData] = useState<PromptWithResponses[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchPrompts = useCallback(async () => {
    if (!topicId) return;

    try {
      setIsLoading(true);
      const response = await fetch(`/api/topics/${topicId}/prompts?withResponses=true`);
      if (!response.ok) throw new Error('Failed to fetch prompts');
      const result = await response.json();
      setData(result);
      setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unknown error');
    } finally {
      setIsLoading(false);
    }
  }, [topicId]);

  useEffect(() => {
    fetchPrompts();
  }, [fetchPrompts]);

  return { data, isLoading, error, refetch: fetchPrompts };
}

export function usePromptResponses(promptId: string) {
  const [data, setData] = useState<LLMResponseDetail[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchResponses = useCallback(async () => {
    if (!promptId) return;

    try {
      setIsLoading(true);
      const response = await fetch(`/api/prompts/${promptId}/responses`);
      if (!response.ok) throw new Error('Failed to fetch responses');
      const result = await response.json();
      setData(result);
      setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unknown error');
    } finally {
      setIsLoading(false);
    }
  }, [promptId]);

  useEffect(() => {
    fetchResponses();
  }, [fetchResponses]);

  return { data, isLoading, error, refetch: fetchResponses };
}
