import { createClient } from '@/lib/supabase/server';
import { NextResponse } from 'next/server';

export async function GET(req: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id } = await params;

    const { data: brand, error } = await supabase
      .from('brands')
      .select(
        `
        *,
        competitors (*),
        topics (*, prompts (*)),
        visibility_metrics (*)
      `
      )
      .eq('id', id)
      .eq('user_id', user.id)
      .single();

    if (error || !brand) {
      return NextResponse.json({ error: 'Brand not found' }, { status: 404 });
    }

    // Sort and limit metrics
    const sortedMetrics = brand.visibility_metrics
      ?.sort(
        (a: { date: string }, b: { date: string }) =>
          new Date(b.date).getTime() - new Date(a.date).getTime()
      )
      .slice(0, 30);

    // Transform to camelCase
    const transformedBrand = {
      id: brand.id,
      name: brand.name,
      domain: brand.domain,
      industry: brand.industry,
      userId: brand.user_id,
      createdAt: brand.created_at,
      updatedAt: brand.updated_at,
      competitors: brand.competitors?.map((c: Record<string, unknown>) => ({
        id: c.id,
        name: c.name,
        domain: c.domain,
        brandId: c.brand_id,
        createdAt: c.created_at,
      })),
      topics: brand.topics?.map((t: Record<string, unknown>) => ({
        id: t.id,
        name: t.name,
        autoGenerated: t.auto_generated,
        brandId: t.brand_id,
        createdAt: t.created_at,
        prompts: (t.prompts as Record<string, unknown>[])?.map((p: Record<string, unknown>) => ({
          id: p.id,
          text: p.text,
          topicId: p.topic_id,
          createdAt: p.created_at,
        })),
      })),
      metrics: sortedMetrics?.map((m: Record<string, unknown>) => ({
        id: m.id,
        brandId: m.brand_id,
        date: m.date,
        visibilityPct: m.visibility_pct,
        avgRank: m.avg_rank,
        citationCount: m.citation_count,
        createdAt: m.created_at,
      })),
    };

    return NextResponse.json(transformedBrand);
  } catch (error) {
    console.error('Failed to fetch brand:', error);
    return NextResponse.json({ error: 'Failed to fetch brand' }, { status: 500 });
  }
}

export async function PATCH(req: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id } = await params;
    const updates = await req.json();

    // Check ownership via RLS - if no row returned, user doesn't own it
    const { data: existingBrand } = await supabase
      .from('brands')
      .select('id')
      .eq('id', id)
      .eq('user_id', user.id)
      .single();

    if (!existingBrand) {
      return NextResponse.json({ error: 'Brand not found' }, { status: 404 });
    }

    const { data: brand, error } = await supabase
      .from('brands')
      .update({
        name: updates.name,
        domain: updates.domain,
        industry: updates.industry,
      })
      .eq('id', id)
      .select('*, competitors (*)')
      .single();

    if (error) {
      console.error('Failed to update brand:', error);
      return NextResponse.json({ error: 'Failed to update brand' }, { status: 500 });
    }

    // Transform to camelCase
    const transformedBrand = {
      id: brand.id,
      name: brand.name,
      domain: brand.domain,
      industry: brand.industry,
      userId: brand.user_id,
      createdAt: brand.created_at,
      updatedAt: brand.updated_at,
      competitors: brand.competitors?.map((c: Record<string, unknown>) => ({
        id: c.id,
        name: c.name,
        domain: c.domain,
        brandId: c.brand_id,
        createdAt: c.created_at,
      })),
    };

    return NextResponse.json(transformedBrand);
  } catch (error) {
    console.error('Failed to update brand:', error);
    return NextResponse.json({ error: 'Failed to update brand' }, { status: 500 });
  }
}

export async function DELETE(req: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id } = await params;

    // Check ownership
    const { data: existingBrand } = await supabase
      .from('brands')
      .select('id')
      .eq('id', id)
      .eq('user_id', user.id)
      .single();

    if (!existingBrand) {
      return NextResponse.json({ error: 'Brand not found' }, { status: 404 });
    }

    const { error } = await supabase.from('brands').delete().eq('id', id);

    if (error) {
      console.error('Failed to delete brand:', error);
      return NextResponse.json({ error: 'Failed to delete brand' }, { status: 500 });
    }

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Failed to delete brand:', error);
    return NextResponse.json({ error: 'Failed to delete brand' }, { status: 500 });
  }
}
