export type LLMProvider = 'OPENAI' | 'ANTHROPIC' | 'GOOGLE';

export interface Brand {
  id: string;
  name: string;
  domain: string;
  industry: string | null;
  userId: string;
  createdAt: Date;
  updatedAt: Date;
  competitors?: Competitor[];
  topics?: Topic[];
  metrics?: VisibilityMetric[];
}

export interface Competitor {
  id: string;
  name: string;
  domain: string;
  brandId: string;
  createdAt: Date;
}

export interface Topic {
  id: string;
  name: string;
  autoGenerated: boolean;
  brandId: string;
  prompts?: Prompt[];
  createdAt: Date;
}

export interface Prompt {
  id: string;
  text: string;
  topicId: string;
  responses?: LLMResponse[];
  createdAt: Date;
}

export interface LLMResponse {
  id: string;
  promptId: string;
  provider: LLMProvider;
  responseText: string;
  mentions?: BrandMention[];
  sources?: CitedSource[];
  createdAt: Date;
}

export interface BrandMention {
  id: string;
  responseId: string;
  brandId: string | null;
  competitorId: string | null;
  brandName: string;
  rankPosition: number | null;
  isCited: boolean;
  context: string | null;
  createdAt: Date;
}

export interface CitedSource {
  id: string;
  responseId: string;
  url: string;
  domain: string;
  title: string | null;
  createdAt: Date;
}

export interface VisibilityMetric {
  id: string;
  brandId: string;
  date: Date;
  visibilityPct: number;
  avgRank: number | null;
  citationCount: number;
  createdAt: Date;
}
