import { requireAuth } from '@/lib/auth-utils';
import { prisma } from '@/lib/db';
import { generateTopics, getSeedTopics } from '@/lib/generators';
import { NextResponse } from 'next/server';

export async function POST(req: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const user = await requireAuth();
    const { id } = await params;
    const { useSeed = false } = await req.json();

    const brand = await prisma.brand.findFirst({
      where: { id, userId: user.id },
    });

    if (!brand) {
      return NextResponse.json({ error: 'Brand not found' }, { status: 404 });
    }

    let topicNames: string[];

    if (useSeed && brand.industry) {
      topicNames = getSeedTopics(brand.industry);
    } else {
      topicNames = await generateTopics(brand.industry || 'software', brand.name, 10);
    }

    if (topicNames.length === 0) {
      return NextResponse.json({ error: 'Failed to generate topics' }, { status: 500 });
    }

    const topics = await Promise.all(
      topicNames.map((name) =>
        prisma.topic.create({
          data: {
            name,
            autoGenerated: true,
            brandId: id,
          },
        })
      )
    );

    return NextResponse.json(topics, { status: 201 });
  } catch (error) {
    if (error instanceof Error && error.message === 'Unauthorized') {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    console.error('Failed to generate topics:', error);
    return NextResponse.json({ error: 'Failed to generate topics' }, { status: 500 });
  }
}
