import { createClient } from '@/lib/supabase/server';
import { generateTopics, getSeedTopics } from '@/lib/generators';
import { NextResponse } from 'next/server';

export async function POST(req: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id } = await params;
    const { useSeed = false } = await req.json();

    // Check brand ownership
    const { data: brand } = await supabase
      .from('brands')
      .select('id, name, industry')
      .eq('id', id)
      .eq('user_id', user.id)
      .single();

    if (!brand) {
      return NextResponse.json({ error: 'Brand not found' }, { status: 404 });
    }

    let topicNames: string[];

    if (useSeed && brand.industry) {
      topicNames = getSeedTopics(brand.industry);
    } else {
      topicNames = await generateTopics(brand.industry || 'software', brand.name, 10);
    }

    if (topicNames.length === 0) {
      return NextResponse.json({ error: 'Failed to generate topics' }, { status: 500 });
    }

    // Insert topics
    const topicsToInsert = topicNames.map((name) => ({
      name,
      auto_generated: true,
      brand_id: id,
    }));

    const { data: topics, error: insertError } = await supabase
      .from('topics')
      .insert(topicsToInsert)
      .select();

    if (insertError) {
      console.error('Failed to insert topics:', insertError);
      return NextResponse.json({ error: 'Failed to create topics' }, { status: 500 });
    }

    // Transform to camelCase
    const formatted = (topics || []).map((t) => ({
      id: t.id,
      name: t.name,
      autoGenerated: t.auto_generated,
      brandId: t.brand_id,
      createdAt: t.created_at,
    }));

    return NextResponse.json(formatted, { status: 201 });
  } catch (error) {
    console.error('Failed to generate topics:', error);
    return NextResponse.json({ error: 'Failed to generate topics' }, { status: 500 });
  }
}
