import { requireAuth } from '@/lib/auth-utils';
import { prisma } from '@/lib/db';
import { NextResponse } from 'next/server';

export async function GET(req: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const user = await requireAuth();
    const { id } = await params;
    const { searchParams } = new URL(req.url);
    const withStats = searchParams.get('withStats') === 'true';

    const brand = await prisma.brand.findFirst({
      where: { id, userId: user.id },
    });

    if (!brand) {
      return NextResponse.json({ error: 'Brand not found' }, { status: 404 });
    }

    if (withStats) {
      const topicsWithStats = await prisma.topic.findMany({
        where: { brandId: id },
        include: {
          prompts: {
            include: {
              responses: {
                include: { mentions: { where: { brandId: id } } },
              },
            },
            orderBy: { createdAt: 'desc' },
          },
        },
        orderBy: { createdAt: 'desc' },
      });

      const result = topicsWithStats.map((topic) => {
        const promptCount = topic.prompts.length;
        const responseCount = topic.prompts.reduce((sum, p) => sum + p.responses.length, 0);
        const mentionCount = topic.prompts.reduce(
          (sum, p) => sum + p.responses.filter((r) => r.mentions.length > 0).length,
          0
        );
        const visibilityPct =
          responseCount > 0 ? Math.round((mentionCount / responseCount) * 100) : 0;

        return {
          id: topic.id,
          name: topic.name,
          autoGenerated: topic.autoGenerated,
          promptCount,
          responseCount,
          visibilityPct,
        };
      });
      return NextResponse.json(result);
    }

    const topics = await prisma.topic.findMany({
      where: { brandId: id },
      include: {
        prompts: {
          orderBy: { createdAt: 'desc' },
        },
      },
      orderBy: { createdAt: 'desc' },
    });

    return NextResponse.json(topics);
  } catch (error) {
    if (error instanceof Error && error.message === 'Unauthorized') {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    console.error('Failed to fetch topics:', error);
    return NextResponse.json({ error: 'Failed to fetch topics' }, { status: 500 });
  }
}

export async function POST(req: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const user = await requireAuth();
    const { id } = await params;
    const { name, autoGenerated = false } = await req.json();

    if (!name) {
      return NextResponse.json({ error: 'Name is required' }, { status: 400 });
    }

    const brand = await prisma.brand.findFirst({
      where: { id, userId: user.id },
    });

    if (!brand) {
      return NextResponse.json({ error: 'Brand not found' }, { status: 404 });
    }

    const topic = await prisma.topic.create({
      data: {
        name,
        autoGenerated,
        brandId: id,
      },
      include: { prompts: true },
    });

    return NextResponse.json(topic, { status: 201 });
  } catch (error) {
    if (error instanceof Error && error.message === 'Unauthorized') {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    console.error('Failed to create topic:', error);
    return NextResponse.json({ error: 'Failed to create topic' }, { status: 500 });
  }
}
