import { createClient } from '@/lib/supabase/server';
import { NextResponse } from 'next/server';

export async function GET(req: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id } = await params;
    const { searchParams } = new URL(req.url);
    const withStats = searchParams.get('withStats') === 'true';

    // Check brand ownership
    const { data: brand } = await supabase
      .from('brands')
      .select('id')
      .eq('id', id)
      .eq('user_id', user.id)
      .single();

    if (!brand) {
      return NextResponse.json({ error: 'Brand not found' }, { status: 404 });
    }

    if (withStats) {
      const { data: topicsWithStats, error } = await supabase
        .from('topics')
        .select(
          `
          *,
          prompts (
            *,
            llm_responses (
              *,
              brand_mentions (*)
            )
          )
        `
        )
        .eq('brand_id', id)
        .order('created_at', { ascending: false });

      if (error) {
        console.error('Failed to fetch topics:', error);
        return NextResponse.json({ error: 'Failed to fetch topics' }, { status: 500 });
      }

      const result = topicsWithStats?.map((topic) => {
        const prompts = topic.prompts || [];
        const promptCount = prompts.length;
        const responseCount = prompts.reduce(
          (sum: number, p: { llm_responses?: unknown[] }) => sum + (p.llm_responses?.length || 0),
          0
        );
        const mentionCount = prompts.reduce(
          (
            sum: number,
            p: {
              llm_responses?: {
                brand_mentions?: { brand_id?: string | null }[];
              }[];
            }
          ) =>
            sum +
            (p.llm_responses?.filter((r) => r.brand_mentions?.some((m) => m.brand_id === id))
              .length || 0),
          0
        );
        const visibilityPct =
          responseCount > 0 ? Math.round((mentionCount / responseCount) * 100) : 0;

        return {
          id: topic.id,
          name: topic.name,
          autoGenerated: topic.auto_generated,
          promptCount,
          responseCount,
          visibilityPct,
        };
      });

      return NextResponse.json(result);
    }

    const { data: topics, error } = await supabase
      .from('topics')
      .select('*, prompts (*)')
      .eq('brand_id', id)
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Failed to fetch topics:', error);
      return NextResponse.json({ error: 'Failed to fetch topics' }, { status: 500 });
    }

    // Transform to camelCase
    const transformed = topics?.map((t) => ({
      id: t.id,
      name: t.name,
      autoGenerated: t.auto_generated,
      brandId: t.brand_id,
      createdAt: t.created_at,
      prompts: t.prompts?.map((p: Record<string, unknown>) => ({
        id: p.id,
        text: p.text,
        topicId: p.topic_id,
        createdAt: p.created_at,
      })),
    }));

    return NextResponse.json(transformed);
  } catch (error) {
    console.error('Failed to fetch topics:', error);
    return NextResponse.json({ error: 'Failed to fetch topics' }, { status: 500 });
  }
}

export async function POST(req: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id } = await params;
    const { name, autoGenerated = false } = await req.json();

    if (!name) {
      return NextResponse.json({ error: 'Name is required' }, { status: 400 });
    }

    // Check brand ownership
    const { data: brand } = await supabase
      .from('brands')
      .select('id')
      .eq('id', id)
      .eq('user_id', user.id)
      .single();

    if (!brand) {
      return NextResponse.json({ error: 'Brand not found' }, { status: 404 });
    }

    const { data: topic, error } = await supabase
      .from('topics')
      .insert({
        name,
        auto_generated: autoGenerated,
        brand_id: id,
      })
      .select('*, prompts (*)')
      .single();

    if (error) {
      console.error('Failed to create topic:', error);
      return NextResponse.json({ error: 'Failed to create topic' }, { status: 500 });
    }

    // Transform to camelCase
    const transformed = {
      id: topic.id,
      name: topic.name,
      autoGenerated: topic.auto_generated,
      brandId: topic.brand_id,
      createdAt: topic.created_at,
      prompts: topic.prompts || [],
    };

    return NextResponse.json(transformed, { status: 201 });
  } catch (error) {
    console.error('Failed to create topic:', error);
    return NextResponse.json({ error: 'Failed to create topic' }, { status: 500 });
  }
}
