'use client';

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { useTopics } from '@/hooks/useTopics';
import { MessageSquare, Plus } from 'lucide-react';
import { PromptList } from './PromptList';

interface TopicAccordionProps {
  brandId: string;
  onAddTopic?: () => void;
}

export function TopicAccordion({ brandId, onAddTopic }: TopicAccordionProps) {
  const { data: topics, isLoading } = useTopics(brandId);

  if (isLoading) {
    return (
      <div className="space-y-2">
        {[1, 2, 3].map((i) => (
          <div key={i} className="h-16 animate-pulse rounded-lg bg-muted" />
        ))}
      </div>
    );
  }

  if (topics.length === 0) {
    return (
      <div className="rounded-lg border border-dashed p-8 text-center">
        <MessageSquare className="mx-auto h-12 w-12 text-muted-foreground" />
        <h3 className="mt-4 text-lg font-semibold">No topics yet</h3>
        <p className="mt-2 text-muted-foreground">
          Create topics to organize your prompts and track visibility by category.
        </p>
        {onAddTopic && (
          <Button onClick={onAddTopic} className="mt-4">
            <Plus className="mr-2 h-4 w-4" />
            Add Topic
          </Button>
        )}
      </div>
    );
  }

  return (
    <Accordion type="multiple" className="space-y-2">
      {topics.map((topic) => (
        <AccordionItem key={topic.id} value={topic.id} className="rounded-lg border bg-card px-4">
          <AccordionTrigger className="hover:no-underline">
            <div className="flex w-full items-center justify-between pr-4">
              <div className="flex items-center gap-2">
                <span className="font-medium">{topic.name}</span>
                {topic.autoGenerated && (
                  <Badge variant="secondary" className="text-xs">
                    Auto
                  </Badge>
                )}
              </div>
              <div className="flex items-center gap-4 text-sm text-muted-foreground">
                <span>{topic.promptCount} prompts</span>
                <span>{topic.responseCount} responses</span>
                <Badge
                  variant={topic.visibilityPct >= 50 ? 'default' : 'secondary'}
                  className={
                    topic.visibilityPct >= 50
                      ? 'bg-green-100 text-green-800 hover:bg-green-100'
                      : topic.visibilityPct >= 25
                        ? 'bg-yellow-100 text-yellow-800 hover:bg-yellow-100'
                        : ''
                  }
                >
                  {topic.visibilityPct}% visibility
                </Badge>
              </div>
            </div>
          </AccordionTrigger>
          <AccordionContent>
            <PromptList topicId={topic.id} />
          </AccordionContent>
        </AccordionItem>
      ))}
    </Accordion>
  );
}
